# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 443cea91be9d58a6eac2fafd4ab9e0ce2b16fb2785c1137f3e14ec7770894c61b985f0d2968ab5ce766688d04db1966673e293505c4c97d381648c1764c769eb

test:
  secret_key_base: dfc8313a207960eed62195745f5fcf87a3cadb008d93288655884760d59dde5c19455905ccba6ac4233fef2a7a2320ed29cc2e6429fda2ec3877ce36d435a041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
